sudo: required

services:
  - docker
  
before_script:
  - docker build -t fastapi-boilerplate -f ./deployment/Dockerfile.test .
  
script:
  - docker run -e ENVIRONMENT='testing' fastapi-boilerplate
g