FROM alpine:latest

RUN apk update && apk add --no-cache build-base python3 python3-dev py3-pip py3-wheel

COPY . /fastapi-boilerplate
WORKDIR /fastapi-boilerplate

RUN pip install --upgrade pip && pip install -r requirements.txt

# TODO: add the test coverage
CMD ["python3", "--version"]
