"""add an example field

Revision ID: a3a1f4356e00
Revises: 6d8b3932dc43
Create Date: 2020-04-21 21:07:22.556563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a1f4356e00'
down_revision = '6d8b3932dc43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_logs', sa.Column('important_field', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_logs', 'important_field')
    # ### end Alembic commands ###
