"""Example migration script

Revision ID: 428163474214
Revises: 199f7366d903
Create Date: 2019-01-01 20:05:37.466545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428163474214'
down_revision = '199f7366d903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_logs', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('api_logs', sa.Column('endpoint', sa.String(length=100), nullable=True))
    op.add_column('api_logs', sa.Column('payload', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_logs', 'payload')
    op.drop_column('api_logs', 'endpoint')
    op.drop_column('api_logs', 'created_at')
    # ### end Alembic commands ###
