name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build -f ./Dockerfile.test -t fastapi-boilerplate .
      - name: Test
        run: docker run -e ENVIRONMENT='testing' fastapi-boilerplate
